import { CategoryInfo } from './types';

export const CATEGORIES: CategoryInfo[] = [
  {
    id: 'all',
    name: 'All Categories',
    icon: 'Folder',
    description: 'Browse the entire 57,000+ vector archive',
    queryKeywords: [],
  },
  {
    id: 'business',
    name: 'Business & Office',
    icon: 'Briefcase',
    description: 'Office gear, briefcases, meetings, finance & corporate clips',
    queryKeywords: ['business', 'office', 'finance', 'meeting', 'money', 'banking', 'briefcase', 'charts', 'corporate'],
  },
  {
    id: 'computers',
    name: 'Computers & Tech',
    icon: 'Monitor',
    description: 'CRT monitors, 3.5" floppy disks, keyboards, modems & tech',
    queryKeywords: ['computer', 'keyboard', 'computing', 'technology', 'mouse', 'internet', 'hardware', 'screens', 'electronic'],
  },
  {
    id: 'cartoons',
    name: 'Cartoons & Cybart',
    icon: 'Smile',
    description: 'The iconic Cybart mascot, comic characters and funny expressions',
    queryKeywords: ['cartoons', 'cybart', 'cartoon', 'comic', 'humor', 'funny', 'characters', 'expressions'],
  },
  {
    id: 'animals',
    name: 'Animals & Wildlife',
    icon: 'Cat',
    description: 'Cats, dogs, dinosaurs, birds, aquatic life & wildlife',
    queryKeywords: ['animals', 'animal', 'dogs', 'cats', 'birds', 'wildlife', 'pets', 'mammals', 'fish', 'dinosaurs', 'fauna'],
  },
  {
    id: 'academic',
    name: 'Academic & School',
    icon: 'GraduationCap',
    description: 'Books, pencils, graduation caps, school supplies & teachers',
    queryKeywords: ['academic', 'education', 'school', 'books', 'students', 'learning', 'graduation', 'science', 'teachers', 'study'],
  },
  {
    id: 'celebrations',
    name: 'Celebrations & Events',
    icon: 'PartyPopper',
    description: 'Balloons, birthday cakes, Christmas, awards, trophies & ribbons',
    queryKeywords: ['celebrations', 'special_occasions', 'holidays', 'awards', 'ribbons', 'christmas', 'birthday', 'trophies', 'prizes', 'party'],
  },
  {
    id: 'people',
    name: 'People & Occupations',
    icon: 'Users',
    description: 'Professions, workers, athletes, doctors, families and portraits',
    queryKeywords: ['people', 'persons', 'men', 'women', 'workers', 'occupations', 'children', 'professionals', 'families'],
  },
  {
    id: 'transportation',
    name: 'Transportation',
    icon: 'Car',
    description: 'Retro automobiles, airplanes, steam trains, ships & rockets',
    queryKeywords: ['transportation', 'cars', 'airplanes', 'vehicles', 'trains', 'aviation', 'boats', 'automobiles', 'travel', 'ships'],
  },
  {
    id: 'food',
    name: 'Food & Dining',
    icon: 'Utensils',
    description: 'Coffee mugs, restaurant items, fruits, pizzas & vintage snacks',
    queryKeywords: ['food', 'dining', 'drinks', 'coffee', 'fruits', 'beverages', 'meals', 'kitchen', 'eating', 'restaurants'],
  },
  {
    id: 'nature',
    name: 'Nature & Plants',
    icon: 'Trees',
    description: 'Trees, flowers, sun, weather, landscapes, globes & botany',
    queryKeywords: ['nature', 'plants', 'flowers', 'trees', 'environment', 'weather', 'landscapes', 'botany', 'gardening'],
  },
  {
    id: 'signs',
    name: 'Signs & Symbols',
    icon: 'HelpCircle',
    description: 'Arrows, idea lightbulbs, question marks, badges, warning signs',
    queryKeywords: ['symbols', 'signs', 'icons', 'arrows', 'concepts', 'badges', 'pointers', 'directions', 'shapes'],
  },
  {
    id: 'healthcare',
    name: 'Healthcare & Medicine',
    icon: 'HeartPulse',
    description: 'Medical instruments, stethoscopes, first aid, pharmacies',
    queryKeywords: ['healthcare', 'medical', 'medicine', 'health', 'doctors', 'hospitals', 'nurses', 'wellness'],
  },
  {
    id: 'sports',
    name: 'Sports & Leisure',
    icon: 'Trophy',
    description: 'Soccer, baseball, golf, swimming, cycling, fitness & games',
    queryKeywords: ['sports', 'recreation', 'athletics', 'games', 'fitness', 'exercise', 'leisure', 'activities'],
  },
  {
    id: 'household',
    name: 'Household & Tools',
    icon: 'Home',
    description: 'Tools, clocks, appliances, keys, real estate & furniture',
    queryKeywords: ['households', 'household', 'tools', 'buildings', 'homes', 'appliances', 'furniture', 'real_estate'],
  },
];
